build/scripts/combined.js, src/index.html, src/scripts/core.js, src/scripts/populate.js, src/scripts/regionalSummary.js, src/styles/main.css
The Regional Summary report is not complete but is functional at the moment so thought it'd be a good idea to merge it into `dev`.
=> Regional summary

src/scripts/query.js
5 categories might be too many to easily distinguish markers sizes, but that number can be easily changed if needed
=> divides peak markers into 5 sizes

src/scripts/core.js
I couldn't find an example of an area in the interest boundary layer with a name supported by the search that wasn't already in the acquisition layer, but if there were such an area, this should work
=> searches interest boundaries when there is not an aquisition boundary

src/index.html, src/scripts/core.js
Added legend that shows active layers and their icons to report.
=> 15 - Issue #15: add legend to pdf report

src/scripts/core.js, src/scripts/query.js
I included the interest boundaries for FWS - if those should stay filled, I'll change it back!
=> Issue #85 - removes fill from polygon features

src/index.html, src/styles/main.css
I'll get rid of the layer icons when I create the legend in Issue 80
=> Issue #77 - move layer toggles to left sidebar

build/index.html, src/scripts/core.js, src/styles/main.css
Instead of making a popup warning when clicking a check box, which got tedious to close each time, there's an updated warning message, the buttons are disabled, and the layers/legend items are removed
=> Issue #107 - Layers & min zoom

README.md, src/index.html
There's a separate issue made for Interpreted, so that isn't fixed in this one.
=> Issue #106 - Collapses layer groups

src/index.html, src/scripts/core.js
Button is open on load, but can be collapsed
=> Issue #98 - Fixes interpreted data button

src/index.html, src/scripts/core.js
=> #60 - disables all buttons on the print modal until map is loaded.

src/scripts/core.js, src/scripts/query.js
this only fixes the event switch. I'll look into the outrageous values Hans found in a separate issue
=> Issue #172 - updates peak legend when using filter modal

src/scripts/core.js, src/scripts/query.js, src/scripts/regionalSummary.js
I didn't do anything about this, but those numbers Hans found yesterday are large because they're elevation
=> Issue #181 - fixes sort

src/scripts/core.js
every time filter modal runs, the layers that were auto-added when the map was first loaded will be turned on (checkboxes checked, legend symbols added)
=> Issue #185 - for layers automatically added, checkboxes & legend on

src/index.html, src/scripts/core.js, src/scripts/regionalSummary.js
unfortunately this requires a long timeout, and I'm worried that could vary widely between computers
=> Issue #194 - force stream gages to load when opening Report

src/index.html, src/scripts/core.js, src/scripts/regionalSummary.js, src/styles/main.css
- Welcome Modal is very simple - I could add more explanation or different buttons, etc.
- After running the Regional Report, it it will go back to the Welcome Modal because there's no event selected
- There's a long wait to generate the site report because it needs to zoom to the location first - I think I'll add in a load warning so the user doesn't click around a bunch while it's running
=> Issue #270 - Refactor welcome modal

src/scripts/core.js, src/scripts/regionalSummary.js
This is a combo of a few short issues: 248, 261, and 260
=> Updates csv buttons, map freeze, and cutoff summary table

src/index.html, src/scripts/core.js, src/styles/main.css
I also deleted the 'Filters' tab because all it did was repeat the event
Looks like this:
=> Issue #270 - reformats sidebar 

src/scripts/core.js, src/scripts/query.js, src/scripts/regionalSummary.js
Code was already there! I just un-commented it. Site report map is already frozen.
=> Issue #299 - freezes regional report map

src/scripts/core.js, src/scripts/query.js
- When there are no peaks, checkbox and label toggle are off and disabled
- When there are 1 or 2 peaks, those peaks get the medium sized diamond and the legend shows just one blue diamond to the left of 'Peak Summary'
=> Issue #292 - update peak symbol in legend when there are <3 peaks

src/index.html
button is kinda long, but I thought it looked better than stacking words and making it a thicker button than the rest
=> Issue #298 - 'Print' to 'Print Full Report'

src/scripts/core.js
- Removes peak and hwm markers that have undefined values from site report
- Also included a minor update to the peak legend for site reports with 1 or 2 peaks
=> Issue #294 - Fixes Waccamaw error

src/scripts/core.js, src/scripts/regionalSummary.js
-also changed 'Survey Date' to 'Survey Date/Time'
=> Issue #354 - Fixes column labels/date formats in csvs and pdfs

src/scripts/core.js
After duplicating the changes from the regional report in Issue #359, the console error disappeared (thanks, Lauren, for figuring it out last month!) It still took me many times to get the report to load, and when it finally did, the gages were still up. However, I don't think those problems are related to this issue, and they might even be improved after Lauren's timing branch is added
=> Issue #380 - fixes undefined error

src/scripts/core.js, src/scripts/regionalSummary.js
I went ahead and put in all checks for undefined values in all fields. For undefined fields other than peak height, I kept the row in the table and just left that cell blank. I figure there may be some undefined values for other fields now or in the future that we haven't discovered yet. I was able to test the peaks ones but didn't know of an hwm with undefined values, but I assume it works. 
All the if statements look a little ridiculous. I tried doing this 
to make it a little neater, but apparently you can't send an undefined value through a function.
=> Fixes #402 - fixes undefined values

src/index.html, src/scripts/core.js, src/scripts/regionalSummary.js, src/styles/misc.css
=> Fixes #417 - removes map from regional report

src/index.html, src/scripts/core.js, src/styles/main.css
I followed the symbols used in the server. Moderate flooding looks just like the storm tide sensor except with a border. I can change it to something else if you want. Doesn't have popups, but they wouldn't take too long to add if there's something else in the data you think they'd like to have.
=> Issue #431 - adds FIMAN

bower.json, code.json, src/scripts/core.js
I'm not proud of the line clip fix lol. I was unable to reproduce so it was hard to actually figure out what the issue was. I'm guessing it's either loading issue or possibly screen size.
I did use Chromes throttling tool to test it at 8 mbs and 3 mbs and it didn't clip.
=> Fiman popup
